export enum ErrorCodes {
    NO_CONTEXT_PERMISSION = "ERROR:FLUEXGL-DSP@0001",
    NO_FILE_TYPE_FOUND = "ERROR:FLUEXGL-DSP@0002",
    PATH_TO_FILE_NOT_FOUND = "ERROR:FLUEXGL-DSP@0003",
    SAME_MASTER_CHANNEL = "ERROR:FLUEXGL-DSP@0004",
    WASM_MODULE_INITIALIZATION_FAILED = "ERROR:FLUEXGL-DSP@0005",
    PATH_TO_WASM_FILE_NOT_FOUND = "ERROR:FLUEXGL-DSP@0006",
    WASM_COMPILATION_ERROR = "ERROR:FLUEXGL-DSP@0007",
    WORKLET_NO_WASM_MODULE_INSTANTIATED = "ERROR:FLUEXGL-DSP@0008",
    EFFECT_ALREADY_ATTACHED = "ERROR:FLUEXGL-DSP@0009",
    EFFECT_NOT_FOUND = "ERROR:FLUEXGL-DSP@0010",
    CHANNEL_ALREADY_ATTACHED = "ERROR:FLUEXGL-DSP@0011",
    CHANNEL_NOT_FOUND = "ERROR:FLUEXGL-DSP@0012",
    CHANNEL_CANNOT_LINK_TO_ITSELF = "ERROR:FLUEXGL-DSP@0013",
    CHANNEL_NOT_INITIALIZED = "ERROR:FLUEXGL-DSP@0014",
    CHANNEL_NOT_SAME_AUDIO_CONTEXT = "ERROR:FLUEXGL-DSP@0015",
    CHANNEL_ALREADY_LINKED = "ERROR:FLUEXGL-DSP@0016",
    CHANNEL_POSSIBLE_FEEDBACK_LOOP = "ERROR:FLUEXGL-DSP@0017",
    AUDIO_CLIP_ALREADY_ATTACHED = "ERROR:FLUEXGL-DSP@0018",
    AUDIO_CLIP_NOT_FOUND = "ERROR:FLUEXGL-DSP@0019",
    AUDIO_CLIP_PLAYER_NO_CONTEXT = "ERROR:FLUEXGL-DSP@0020",
    PANNING_OUT_OF_RANGE = "ERROR:FLUEXGL-DSP@0021",
    PITCH_OUT_OF_RANGE = "ERROR:FLUEXGL-DSP@0022",
    INPUT_DEVICE_UNAVAILABLE = "ERROR:FLUEXGL-DSP@0023",
    OUTPUT_DEVICE_UNAVAILABLE = "ERROR:FLUEXGL-DSP@0024"
}

export enum WarningCodes {
    NO_DEFAULT_AUDIO_DEVICE_FOUND = "WARNING:FLUEXGL-DSP@0001",
    OUTPUT_DEVICE_SWITCH_UNSUPPORTED = "WARNING:FLUEXGL-DSP@0002",
    OUTPUT_DEVICE_LOST = "WARNING:FLUEXGL-DSP@0003",
    INPUT_DEVICE_LOST = "WARNING:FLUEXGL-DSP@0004",
    CHANNEL_NOT_ATTACHED = "WARNING:FLUEXGL-DSP@0005",
    CHANNEL_ALSO_SENT_TO_MASTER = "WARNING:FLUEXGL-DSP@0006"
}

export enum SuccessCodes {

}