export enum ErrorCodes {
    NO_CONTEXT_PERMISSION = "ERROR:FLUEXGL-DSP@0001",
    NO_FILE_TYPE_FOUND = "ERROR:FLUEXGL-DSP@0002",
    PATH_TO_FILE_NOT_FOUND = "ERROR:FLUEXGL-DSP@0003",
    SAME_MASTER_CHANNEL = "ERROR:FLUEXGL-DSP@0004",
    WASM_MODULE_INITIALIZATION_FAILED = "ERROR:FLUEXGL-DSP@0005",
    PATH_TO_WASM_FILE_NOT_FOUND = "ERROR:FLUEXGL-DSP@0006"
}

export enum WarningCodes {
    NO_DEFAULT_AUDIO_DEVICE_FOUND = "WARNING:FLUEXGL-DSP@0001"
}

export enum SuccessCodes {

}